context:
  version: "3.2"

package:
  name: hstr
  version: ${{ version }}

source:
  url: https://github.com/dvorka/hstr/archive/v${{ version }}.tar.gz
  sha256: bceab1cb3c3b636d9ff4dfbaf8b035530e76a36d948767ed1735c4e79d7473eb

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - pkg-config
    - make
    - sed
  host:
    - bash-completion
    - libtool
    - readline
    - ncurses
  run:
    - bash-completion

tests:
  - script:
      - hh --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Bash and zsh history suggest box
  homepage: https://github.com/dvorka/hstr
  repository: https://github.com/dvorka/hstr

extra:
  recipe-maintainers:
    - danielnachun
